### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#126]
* [x]  review code compare to spec, note which features work yet
* [x] initial testing for errors loading etc
* [x] update the manual to include player commands added
* [x] update the /ehelp docs
* [x] update our major release version reply
* [x] disable any crazy mad scientist crap i am working on
* [x] upload to workshop
* [x] update release version notes
* [x] comment on the workshop and facebook page announcing release
* [x] go to sleep before your brain explodes
* [x] review admin econfig commands and add to manual
* [x] review milestone can we close it etc
