### ISSUE TITLE
TODO: shortened lazy a$$ commands for some tasks

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#135]
A lot of the tech support requests I get are from people trying to use commands without entering all the correct parameters.   For some reason the "you need to specify X"  text in game, and the detailed manual explaining each command and its parameters seems to be getting ignored.. overlooked, or they lack the ability to read English?   Or some admins have poor memories, or some parameters are using pretty common configurations anyway and it may save a little monotony/repetition.

* [x] add zone here  /npczone addhere <name>  Optional_size
* [x] move zone here /npczone movehere <name> 
* [x] quickadd (addhere works with or without radius)   see addhere above
* [x] pay player for no reason /pay bob 1234

(Note to self - Should we support "lazy player" versions of these in /tz ?  Nope that uses beacons. All good.)

**Comment by jpcsupplies** [comment]
..  no doubt @midspace you will add 2 character to your regex, and one line of code that replaces the entire thing :P  but i'm having fun here

**Comment by jpcsupplies** [comment]
You wanna take a look at these to make sure I dont burn someones house down with my code :)

**Comment by jpcsupplies** [comment]
just rewrote the description on original post, i just realized my grammar was terrible and what i was asking made no sense at all! lol

**Comment by jpcsupplies** [comment]
Ok have pushed out the build with these changes to public version.  It does contain one minor bug - the movehere parameters do not preserve the size and shape of the original zone being moved, it uses the default zone size.
