### ISSUE TITLE
TODO: Configurable options can be changed in the config file

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#78]
Many of the options currently in our constants file should be available in our config XML file, to allow admins to customise the behaviour of their server.
The constants will then be treated as the "defaults" if this file does not exist, but read from the file instead if it does exist.

Eg
- [x] DefaultStartingBalance = 100; //new player balance
- [x] NPCStartingBalance = 20000; //non-player trade network funds
- [x] LimitedRange = false; //must we be near each other to trade
- [x] DefaultTradeRange = 2500; //how close do we need to be to trade
- [x] LimitedSupply = true; //should the non-player market have unlimited resources and money
- [x] NpcMerchantName = "_Default_NPC_Merchant_"; //whats our non-player merchant name
- [x] TradeTimeoutMinutes = 2; //how long to wait before cancelling a sell offer

Also later on things like:
- [x] CurrencyName ="Credits"; //Space Bucks, Marscoin, magic beans whatever
- [x] TradeNetworkName ="Blue Mining Inc"; //on join: Economy Loaded, welcome to the Blue Mining Inc Frontier Trade Network etc

**Comment by midspace** [comment]
Have updated the above with checkbox, which indicate the progress.

**Comment by jpcsupplies** [comment]
ok cool; didnt even know you could do that  :)

**Comment by midspace** [comment]
All objectives complete.
